### ISSUE TITLE
[Bug]: "/controller/manager": permission denied: unknown

### ISSUE THREAD

**Issue by sr12344321** [cloudnative-pg/cloudnative-pg#5199] opened 2024-07-30 11:23 UTC
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

sr12344321@gmail.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

I test on minikube and work all ok.. now I tray to install on on-prem k8s but I cant find what I do wrong or is same bug.
Operator is installed ok, but when I tray to create cluster I gat this 
error:  Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/controller/manager": permission denied: unknown

my cluster-pg.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: cloudnative-pg
spec:
  instances: 2
  storage:
    #storageClass: local-hostpath
    size: 3Gi

### Cluster resource

```shell
k get pods -n cloudnative-pg
NAME                             READY   STATUS       RESTARTS      AGE
cluster-example-1-initdb-6mgp4   0/1     StartError   0             6m53s
cluster-example-1-initdb-mmxm9   0/1     StartError   0             7m57s
cluster-example-1-initdb-nw8xp   0/1     StartError   0             8m14s
cluster-example-1-initdb-rf7mr   0/1     StartError   0             2m51s
cluster-example-1-initdb-xpr2w   0/1     StartError   0             5m32s
cluster-example-1-initdb-zbstb   0/1     StartError   0             7m35s
```

### Relevant log output

```shell
k logs pod -n cloudnative-pg  cluster-example-1-initdb-nw8xp
error: error from server (NotFound): pods "pod" not found in namespace "cloudnative-pg"
 Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/controller/manager": permission denied: unknown

operator log:
2024-07-30T12:35:57.000530164+02:00 {"debug":"info","ts":"2024-07-30T10:35:57Z","logger":"pki","msg":"Periodic TLS certificates maintenance"}

2024-07-30T12:38:53.031645136+02:00 {"debug":"info","ts":"2024-07-30T10:38:53Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"65883313-207d-4538-871c-b1105887b8b8","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:38:53.088841071+02:00 {"debug":"info","ts":"2024-07-30T10:38:53Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"49855724-4f18-4dbb-838f-e3b1c08a36b4","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:38:53.675545465+02:00 {"debug":"info","ts":"2024-07-30T10:38:53Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"7ac7e002-fbf1-49fe-8ef7-82cc7afc7e31","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:38:54.736644801+02:00 {"debug":"info","ts":"2024-07-30T10:38:54Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"7e7d915b-d38f-46ed-b96a-2cdddbf12417","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:38:55.781981656+02:00 {"debug":"info","ts":"2024-07-30T10:38:55Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"4724a1fc-afbc-4a21-8d8f-e4e070a2c35e","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:38:56.834527657+02:00 {"debug":"info","ts":"2024-07-30T10:38:56Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"f1c879f6-376f-4a3c-8352-027b23833127","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:38:58.232565497+02:00 {"debug":"info","ts":"2024-07-30T10:38:58Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"5599be4c-f6b2-4eb6-8a65-766fad26f184","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:38:59.286204817+02:00 {"debug":"info","ts":"2024-07-30T10:38:59Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"762422c7-a7de-461d-bf8f-06b39e534fae","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:00.324125987+02:00 {"debug":"info","ts":"2024-07-30T10:39:00Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"ab9a0067-c265-4418-ae6b-a28d22a7b996","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:01.381446938+02:00 {"debug":"info","ts":"2024-07-30T10:39:01Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"8516ccac-2b00-425b-8aa4-51b0f1d9a805","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:02.437919480+02:00 {"debug":"info","ts":"2024-07-30T10:39:02Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"12bb32bd-ac6f-44c4-9a79-82466ec3839e","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:03.483042778+02:00 {"debug":"info","ts":"2024-07-30T10:39:03Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"78df70e6-8e31-456a-89ce-e9dc13546cae","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:04.531261289+02:00 {"debug":"info","ts":"2024-07-30T10:39:04Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"0efc5567-2ecd-4544-a833-13d9d4f3487e","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:05.573449658+02:00 {"debug":"info","ts":"2024-07-30T10:39:05Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"5fde6ea8-a823-4cb2-9c31-2109df4dfee8","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:06.615440133+02:00 {"debug":"info","ts":"2024-07-30T10:39:06Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"8cab7fc1-2894-4086-8757-e314353fc31d","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:07.658360756+02:00 {"debug":"info","ts":"2024-07-30T10:39:07Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"ecf8f775-6e53-44a5-a8e9-d8d0243d6c84","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:08.700991836+02:00 {"debug":"info","ts":"2024-07-30T10:39:08Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"7b3d6f73-4f00-4b1b-8a3a-99dc1bedccec","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:09.849163204+02:00 {"debug":"info","ts":"2024-07-30T10:39:09Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"214ba7fe-dc4a-447f-a1a0-7ac68600de9f","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:10.897017654+02:00 {"debug":"info","ts":"2024-07-30T10:39:10Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"6b918782-dd41-4f3e-8e1a-801e883d90dd","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:11.962611212+02:00 {"debug":"info","ts":"2024-07-30T10:39:11Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"3f2bdd39-ad5a-4e24-ad4b-f300808dfb30","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:13.002136495+02:00 {"debug":"info","ts":"2024-07-30T10:39:13Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"04c19ce2-3167-425e-97bd-6b3b6cc11b0c","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:14.055957166+02:00 {"debug":"info","ts":"2024-07-30T10:39:14Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"417913cc-dc50-4a80-b5b9-a3e17d4482f3","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:15.108136243+02:00 {"debug":"info","ts":"2024-07-30T10:39:15Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"7afeb576-974c-442b-b15f-862050ae6c04","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:16.160800887+02:00 {"debug":"info","ts":"2024-07-30T10:39:16Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"24ffbc81-0c78-4263-b0be-031900b26584","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:17.203650350+02:00 {"debug":"info","ts":"2024-07-30T10:39:17Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"718dd86c-a4df-4fa1-84d7-ef2835971e4b","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:18.250793789+02:00 {"debug":"info","ts":"2024-07-30T10:39:18Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"afc423b1-59d1-490a-a05b-fff656c5f073","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:19.546840671+02:00 {"debug":"info","ts":"2024-07-30T10:39:19Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"bd879ad1-b640-422e-b014-968a864d73c8","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:20.594230917+02:00 {"debug":"info","ts":"2024-07-30T10:39:20Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"084de313-0472-46ae-ac27-4f54e461fb44","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:21.646602125+02:00 {"debug":"info","ts":"2024-07-30T10:39:21Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"d19b0494-891e-444d-96d8-5fe82d875fb1","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:22.693602501+02:00 {"debug":"info","ts":"2024-07-30T10:39:22Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"db57983b-d59f-4c19-9594-466d9a6ff39e","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:23.739246607+02:00 {"debug":"info","ts":"2024-07-30T10:39:23Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"6e8501a7-fe1a-441f-b248-b7e99f0e15c9","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:24.793774175+02:00 {"debug":"info","ts":"2024-07-30T10:39:24Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"3e1dcc2f-04ab-4cde-a06f-24c81b0479d8","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:25.837770806+02:00 {"debug":"info","ts":"2024-07-30T10:39:25Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"a083f6bc-a3b5-4f9f-a962-284c1bdce51c","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:26.883052673+02:00 {"debug":"info","ts":"2024-07-30T10:39:26Z","msg":"Selected PVC is not ready yet, waiting for 1 second","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"570f47a3-8102-462b-8130-7c9def84d601","pvc":"cluster-example-1","status":"initializing","instance":"cluster-example-1"}

2024-07-30T12:39:27.417690386+02:00 {"debug":"info","ts":"2024-07-30T10:39:27Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"1c70fc5b-85d9-455b-b961-ce199f25b2fa"}

2024-07-30T12:39:27.492349157+02:00 {"debug":"info","ts":"2024-07-30T10:39:27Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"17fb13c1-2684-4f90-828b-76fba0762c37"}

2024-07-30T12:39:27.517862092+02:00 {"debug":"info","ts":"2024-07-30T10:39:27Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"d294cbb1-9d3f-43b7-b514-e8a45b6ee67f"}

2024-07-30T12:39:27.526116480+02:00 {"debug":"info","ts":"2024-07-30T10:39:27Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"ed5496dd-f9f6-4fcc-9ed9-45343630b9c9"}

2024-07-30T12:39:27.884258403+02:00 {"debug":"info","ts":"2024-07-30T10:39:27Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"d9af1b04-2c6c-4e7e-afd5-00e975067fcb"}

2024-07-30T12:40:12.461585051+02:00 {"debug":"info","ts":"2024-07-30T10:40:12Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"2c162a8f-0a24-493c-ab88-c8eee4713e66"}

2024-07-30T12:40:26.655723740+02:00 {"debug":"info","ts":"2024-07-30T10:40:26Z","logger":"cluster-resource","msg":"default","version":"v1","name":"cluster-example","namespace":"cloudnative-pg"}

2024-07-30T12:40:26.661395232+02:00 {"debug":"info","ts":"2024-07-30T10:40:26Z","logger":"cluster-resource","msg":"validate create","version":"v1","name":"cluster-example","namespace":"cloudnative-pg"}

2024-07-30T12:40:26.682812316+02:00 {"debug":"info","ts":"2024-07-30T10:40:26Z","msg":"no orphan PVCs found, skipping the restored cluster reconciliation","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"34485bd5-eb77-4fde-a6c6-a45e4d903dd2"}

2024-07-30T12:40:26.947355906+02:00 {"debug":"info","ts":"2024-07-30T10:40:26Z","msg":"Creating new Job","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"34485bd5-eb77-4fde-a6c6-a45e4d903dd2","name":"cluster-example-1-initdb","primary":true}

2024-07-30T12:53:56.071943550+02:00 {"debug":"info","ts":"2024-07-30T10:53:56Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"7a0e7cc5-660a-45aa-85dc-097a70f7e976"}

2024-07-30T12:53:56.098744667+02:00 {"debug":"info","ts":"2024-07-30T10:53:56Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"78841c53-6a90-4a28-b1a7-bf46f84dc38a"}

2024-07-30T12:53:56.132625263+02:00 {"debug":"info","ts":"2024-07-30T10:53:56Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"cc172838-8228-47fd-bdfa-a5372b19a069"}

2024-07-30T12:53:56.147924259+02:00 {"debug":"info","ts":"2024-07-30T10:53:56Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"c08b45d3-7bfd-4618-ae46-4bf897cc304e"}

2024-07-30T12:53:56.300719114+02:00 {"debug":"info","ts":"2024-07-30T10:53:56Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"50bd8387-d170-41dd-a6a8-25b45cecce01"}

2024-07-30T12:53:56.456450738+02:00 {"debug":"info","ts":"2024-07-30T10:53:56Z","msg":"Resource has been deleted","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"f2ee5358-c75c-481d-b3de-6d7433d0462c"}

2024-07-30T12:54:09.431347120+02:00 {"debug":"info","ts":"2024-07-30T10:54:09Z","logger":"cluster-resource","msg":"default","version":"v1","name":"cluster-example","namespace":"cloudnative-pg"}

2024-07-30T12:54:09.440486163+02:00 {"debug":"info","ts":"2024-07-30T10:54:09Z","logger":"cluster-resource","msg":"validate create","version":"v1","name":"cluster-example","namespace":"cloudnative-pg"}

2024-07-30T12:54:09.467292180+02:00 {"debug":"info","ts":"2024-07-30T10:54:09Z","msg":"no orphan PVCs found, skipping the restored cluster reconciliation","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"e88fbbb9-55a5-4327-9c4a-9dde6b46fe5f"}

2024-07-30T12:54:09.980175338+02:00 {"debug":"info","ts":"2024-07-30T10:54:09Z","msg":"Creating new Job","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"cloudnative-pg"},"namespace":"cloudnative-pg","name":"cluster-example","reconcileID":"e88fbbb9-55a5-4327-9c4a-9dde6b46fe5f","name":"cluster-example-1-initdb","primary":true}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment] 2024-07-30 11:28
Hello @sr12344321 

This is a problem of the PVC not being ready, probably the PV it's not being provided, since the operator give up and try , the next time may found the pvc ready but without the controller, please check the status of PV

Regards,

**Comment by sxd** [comment] 2024-07-30 11:33
Closing since there's no proves this is a bug on the operator but a kubernetes issue

**Closed by sxd** 2024-07-30 11:33 UTC

**Comment by sr12344321** [comment] 2024-07-30 13:44
thx for quick response. 
I tray with manual crate PV and same error. 
```
k get sc,pv,pvc
NAME                                                     PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
storageclass.storage.k8s.io/openebs-device               openebs.io/local               Delete          WaitForFirstConsumer   false                  27h
storageclass.storage.k8s.io/openebs-hostpath (default)   openebs.io/local               Delete          WaitForFirstConsumer   false                  27h
storageclass.storage.k8s.io/openebs-k8s                  openebs.io/local               Delete          WaitForFirstConsumer   true                   3m43s
storageclass.storage.k8s.io/test                         kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  56s

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                             STORAGECLASS       VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/local-pv                                   4Gi        RWO            Retain           Bound    cloudnative-pg/cluster-example-1                                  test               <unset>                          46s
persistentvolume/pvc-605d62fc-f1cc-4b7c-ade4-3bdb4b8ff015   10Gi       RWO            Delete           Bound    cloudnative-pg/postgres-test                                      openebs-hostpath   <unset>                          3h39m
```

on node:
`drwxrwxrwx 2 root root 6 2024-07-30 14:09 pv-data`

and this is from openebs storageclass localpath.
```
k get sc,pv,pvc
NAME                                                     PROVISIONER        RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
storageclass.storage.k8s.io/openebs-device               openebs.io/local   Delete          WaitForFirstConsumer   false                  27h
storageclass.storage.k8s.io/openebs-hostpath (default)   openebs.io/local   Delete          WaitForFirstConsumer   false                  27h
storageclass.storage.k8s.io/openebs-k8s                  openebs.io/local   Delete          WaitForFirstConsumer   true                   94s

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                             STORAGECLASS       VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/pvc-605d62fc-f1cc-4b7c-ade4-3bdb4b8ff015   10Gi       RWO            Delete           Bound    cloudnative-pg/postgres-test                                      openebs-hostpath   <unset>                          3h37m
persistentvolume/pvc-a972fcdf-e899-4f31-9b59-a585ec67b12d   3Gi        RWO            Delete           Bound    cloudnative-pg/cluster-example-1                                  openebs-k8s        <unset>                          62s
```

I don't now what else I can  tray to make this working.. I have with same storageclass working postgres container with working pv...

any suggestion what I need to test on PV?

**Comment by hegerdes** [comment] 2024-09-23 15:01
I faced the same issue on an OpenShift Cluster. It's not the operators fault.

The problem is that the user for the init container a different one then the "main" container. The manager binary has the hardcoded permissions `0750` and when the main container runs as a different user and user group you get permission denied. 

Since you can't set `runAs` for the containers/pods secucrity context (AFAIK) because the operator generates the pod template for you it uses random UIDs and then they dont match, at least in the OpenShift world.

Solution was to create a scc that forces the pods contains to run as `uid: 65532` and bind that scc to all pods created by cloudnative-pg
