### ISSUE TITLE
[Bug]: phantom error after initdb removal

### ISSUE THREAD

**Issue by zifeo** [cloudnative-pg/cloudnative-pg#5881] opened 2024-10-17 13:40 UTC
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: RKE

### How did you install the operator?

Helm

### What happened?

The cluster was provisioned with an initdb, however after sometimes, it became clear that the virtual databases (many of them) will be managed externally (yes, I know this is not recommended), so the initial initdb was removed using psql. Since then, all the database pod keep seeing the following error probing the database that does not exist anymore. Note that the initdb section was also removed from the cluster manifest but it keeps getting back. How can the initdb be removed correctly?

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
  name: account-db
  namespace: ns
 spec:
  affinity:
    podAntiAffinityType: preferred
  backup:
    barmanObjectStore:
      destinationPath: s3://bucket/account
      endpointURL: https://redacted
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: aws-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: aws-creds
      wal:
        compression: gzip
        maxParallel: 8
    retentionPolicy: 7d
    target: prefer-standby
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
  enablePDB: true
  enableSuperuserAccess: true
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:15.7
  instances: 2
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: 'on'
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: '0'
      log_rotation_size: '0'
      log_statement: all
      log_truncate_on_rotation: 'false'
      logging_collector: 'on'
      max_parallel_workers: '32'
      max_replication_slots: '32'
      max_worker_processes: '32'
      shared_memory_type: mmap
      shared_preload_libraries: ''
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: 'on'
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
  smartShutdownTimeout: 180
  startDelay: 60
  stopDelay: 60
  storage:
    resizeInUseVolumes: true
    size: 10Gi
    storageClass: retain
  superuserSecret:
    name: account-user
  switchoverDelay: 3600
  walStorage:
    resizeInUseVolumes: true
    size: 5Gi
    storageClass: retain
```

### Relevant log output

```shell
{"level":"error","ts":"2024-10-17T11:32:20Z","msg":"Error collecting user query","query":"backends","logging_pod":"account-db-2","targetDatabase":"app","error":"failed to connect to `user=postgres database=app`: /controller/run/.s.PGSQL.5432 (/controller/run): server error: FATAL: database \"app\" does not exist (SQLSTATE 3D000)","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/metrics.(*QueriesCollector).collectUserQueries\n\tpkg/management/postgres/metrics/collector.go:131\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/metrics.QueriesCollector.Collect\n\tpkg/management/postgres/metrics/collector.go:64\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver/metricserver.(*Exporter).collectPgMetrics\n\tpkg/management/postgres/webserver/metricserver/pg_collector.go:369\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver/metricserver.(*Exporter).Collect\n\tpkg/management/postgres/webserver/metricserver/pg_collector.go:298\ngithub.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1\n\tpkg/mod/github.com/prometheus/client_golang@v1.20.0/prometheus/registry.go:456"}
{"level":"error","ts":"2024-10-17T11:32:20Z","msg":"Error collecting user query","query":"pg_replication_slots","logging_pod":"account-db-2","targetDatabase":"app","error":"failed to connect to `user=postgres database=app`: /controller/run/.s.PGSQL.5432 (/controller/run): server error: FATAL: database \"app\" does not exist (SQLSTATE 3D000)","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/metrics.(*QueriesCollector).collectUserQueries\n\tpkg/management/postgres/metrics/collector.go:131\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/metrics.QueriesCollector.Collect\n\tpkg/management/postgres/metrics/collector.go:64\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver/metricserver.(*Exporter).collectPgMetrics\n\tpkg/management/postgres/webserver/metricserver/pg_collector.go:369\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver/metricserver.(*Exporter).Collect\n\tpkg/management/postgres/webserver/metricserver/pg_collector.go:298\ngithub.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1\n\tpkg/mod/github.com/prometheus/client_golang@v1.20.0/prometheus/registry.go:456"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment] 2024-10-31 09:39
I am closing this ticket as it is an expected behaviour, not a bug. The 'initdb' bootstrap method is the default one.

Please refer to:

- https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-BootstrapConfiguration
- https://cloudnative-pg.io/documentation/current/monitoring/#monitoring-instances

Thank you.

**Closed by gbartolini** 2024-10-31 09:39 UTC
Labels: triage

**Comment by zifeo** [comment] 2024-10-31 11:48
@gbartolini Can you please re-read my report? I never mentioned that this is an unexpected behavior, rather than the operator should support the removal of the monitoring when the initdb is gone, or feel free to suggest an alternative. As such the operator should provide a way to escape that situation, not stay in a continuous error state.

**Comment by zifeo** [comment] 2024-11-21 10:50
@gbartolini Should I open another ticket such a feature request?
