### ISSUE TITLE
Pod restarting because of pg_isready timeout

### ISSUE THREAD

**Issue by jarlebh** [cloudnative-pg/cloudnative-pg#793] opened 2022-09-30 12:46 UTC
When the DB is under heavy load over time this happens. The consequence is a db restart and potential data loss.
Is it possible to extend the timeout for the liveness probe ? Or do you have any idea why the pg_isready would answer slowly.

See below for log from the pod.

> 
> {"level":"info","ts":1664531560.1691935,"msg":"Liveness probe failing","logging_pod":"postgres-webmed-test1-1","err":"could not establish connection"}
> {"level":"info","ts":1664531566.3779688,"logger":"postgres","msg":"record","logging_pod":"postgres-webmed-test1-1","record":{"log_time":"2022-09-30 09:52:46.375 UTC","user_name":"postgres","database_name":"postgres","process_id":"221410","connection_from":"[local]","session_id":"6336bc65.360e2","session_line_num":"1","command_tag":"idle","session_start_time":"2022-09-30 09:52:37 UTC","virtual_transaction_id":"22/0","transaction_id":"0","error_severity":"LOG","sql_state_code":"08006","message":"could not send data to client: Broken pipe","application_name":"pg_isready","backend_type":"client backend","query_id":"0"}}
> {"level":"info","ts":1664531566.3781583,"logger":"postgres","msg":"record","logging_pod":"postgres-webmed-test1-1","record":{"log_time":"2022-09-30 09:52:46.375 UTC","user_name":"postgres","database_name":"postgres","process_id":"221410","connection_from":"[local]","session_id":"6336bc65.360e2","session_line_num":"2","command_tag":"idle","session_start_time":"2022-09-30 09:52:37 UTC","virtual_transaction_id":"22/0","transaction_id":"0","error_severity":"FATAL","sql_state_code":"08006","message":"connection to client lost","application_name":"pg_isready","backend_type":"client backend","query_id":"0"}}
> {"level":"info","ts":1664531570.166364,"msg":"Liveness probe failing","logging_pod":"postgres-webmed-test1-1","err":"could not establish connection"}
> {"level":"info","ts":1664531575.5547562,"logger":"postgres","msg":"record","logging_pod":"postgres-webmed-test1-1","record":{"log_time":"2022-09-30 09:52:55.554 UTC","user_name":"postgres","database_name":"postgres","process_id":"221416","connection_from":"[local]","session_id":"6336bc6f.360e8","session_line_num":"1","command_tag":"idle","session_start_time":"2022-09-30 09:52:47 UTC","virtual_transaction_id":"22/0","transaction_id":"0","error_severity":"LOG","sql_state_code":"08006","message":"could not send data to client: Broken pipe","application_name":"pg_isready","backend_type":"client backend","query_id":"0"}}
> {"level":"info","ts":1664531575.5548055,"logger":"postgres","msg":"record","logging_pod":"postgres-webmed-test1-1","record":{"log_time":"2022-09-30 09:52:55.554 UTC","user_name":"postgres","database_name":"postgres","process_id":"221416","connection_from":"[local]","session_id":"6336bc6f.360e8","session_line_num":"2","command_tag":"idle","session_start_time":"2022-09-30 09:52:47 UTC","virtual_transaction_id":"22/0","transaction_id":"0","error_severity":"FATAL","sql_state_code":"08006","message":"connection to client lost","application_name":"pg_isready","backend_type":"client backend","query_id":"0"}}
> {"level":"info","ts":1664531580.1647916,"msg":"Liveness probe failing","logging_pod":"postgres-webmed-test1-1","err":"could not establish connection"}
> {"level":"info","ts":1664531580.1785934,"msg":"Received termination signal","logging_pod":"postgres-webmed-test1-1","signal":"interrupt"}
> {"level":"info","ts":1664531580.1786296,"msg":"Requesting smart shutdown of the PostgreSQL instance","logging_pod":"postgres-webmed-test1-1"}
> {"level":"info","ts":1664531583.0415192,"logger":"postgres","msg":"record","logging_pod":"postgres-webmed-test1-1","record":{"log_time":"2022-09-30 09:53:03.041 UTC","user_name":"postgres","database_name":"webmed","process_id":"221407","connection_from":"[local]","session_id":"6336bc64.360df","session_line_num":"1","command_tag":"SELECT","session_start_time":"2022-09-30 09:52:36 UTC","virtual_transaction_id":"19/517311","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"duration: 26402.679 ms plan:\nQuery Text: SELECT datname\n , pg_catalog.pg_database_size(datname) AS size_bytes\n , pg_catalog.age(datfrozenxid) AS xid_age\n , pg_catalog.mxid_age(datminmxid) AS mxid_age\nFROM pg_catalog.pg_database\n\nSeq Scan on pg_database (cost=0.00..1.03 rows=2 width=80)","application_name":"cnpg_metrics_exporter","backend_type":"client backend","query_id":"-7688591772378490058"}}
> {"level":"info","ts":1664531583.0421717,"logger":"pg_ctl","msg":"pg_ctl: server is running (PID: 6024)\n/usr/lib/postgresql/14/bin/postgres \"-D\" \"/var/lib/postgresql/data/pgdata\"\n","pipe":"stdout","logging_pod":"postgres-webmed-test1-1"}
> {"level":"info","ts":1664531583.042243,"msg":"Shutting down instance","logging_pod":"postgres-webmed-test1-1","pgdata":"/var/lib/postgresql/data/pgdata","mode":"smart","timeout":15}
> {"level":"info","ts":1664531583.0824351,"logger":"postgres","msg":"record","logging_pod":"postgres-webmed-test1-1","record":{"log_tim

**Comment by dspeck1** [comment] 2022-10-13 19:20
We also see this same behavior.  Failover takes a couple minutes so is disruptive.  Thoughts on increasing readiness timeout value?

**Comment by gbartolini** [comment] 2022-11-01 01:33
Could this be a duplicate of #889 and as such be resolved by #890?

**Comment by jarlebh** [comment] 2022-11-01 05:31
I dont think so since this is caused by pg_isready taking too long to
respond. It is called however the liveness probe times out.

Jarle

tir. 1. nov. 2022, 02:33 skrev Gabriele Bartolini ***@***.***

**Closed** 2022-12-30 20:16 UTC
