### ISSUE TITLE
WAL archiving in "Starting up

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#1603] opened 2023-03-01 07:43 UTC
```
Continuous Backup status
First Point of Recoverability:  2023-02-28T18:03:54Z
Working WAL archiving:          Starting Up
WALs waiting to be archived:    0
Last Archived WAL:              -
Last Failed WAL:                -
```

**Comment by mnencia** [comment] 2023-03-01 15:23
Duplicate of #1604

**Closed by mnencia** 2023-03-01 15:23 UTC
