### ISSUE TITLE
[Feature]: Restart primary instead of failing-over to replica on configuration change if replica has considerable lag

### ISSUE THREAD

**Issue by Eykha** [cloudnative-pg/cloudnative-pg#5092] opened 2024-07-15 15:00 UTC
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Assuming you have a cluster with 2 instances. 
When ingesting a lot of data over a longer time period, the replication lag can become quite high. 
When meanwhile performing an update on the cluster resource that triggers a failover, I observed the following:
1. Primary will shut down 
2. Primary will upload outstanding WALs
3. Replica will continue to synchronize until all WALs have been replayed
4. Replica will assume role as Primary

If replication lag was high, this results in a downtime going on until the replica is back in sync.

### Describe the solution you'd like

I would like to have a check in place to see if the replica is currently in sync, given a specific threshold. If the replica is not in sync, the primary should be restarted in place and continue its role as primary.

### Describe alternatives you've considered

I cannot think of an alternative.

### Additional context

#5000 and #3971 might be somewhat related.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment] 2024-07-16 06:06
I think you are probably confusing failover with switchover. Failover cannot be controlled, it is caused by an unexpected event and the only option is to promote the most advanced replica or wait (`failoverDelay`).

As far as controlled switchover is concerned, what you are asking has been fixed with PR #4288

**Closed by gbartolini** 2024-07-16 06:06 UTC
Labels: triage

**Comment by Eykha** [comment] 2024-07-16 07:23
Yes, I confused the two terms. Thanks for the clarification
