### ISSUE TITLE
[Bug]: error when patching "/dev/shm/3027502448": CustomResourceDefinition.apiextensions.k8s.io "poolers.postgresql.cnpg.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by DevBey** [cloudnative-pg/cloudnative-pg#4449] opened 2024-05-07 12:31 UTC
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

devansh.choubey@kavida.ai

### Version

1.23.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

Helm

### What happened?

we are using argocd for deployment, we are getting this error while updating the postgres application with new version. or something else.  

### Cluster resource

```shell
we are just using the default CR from the helm chart. with affinity for a node.
```

### Relevant log output

```shell
Failed sync attempt to : one or more objects failed to apply, reason: error when patching "/dev/shm/1134612930": CustomResourceDefinition.apiextensions.k8s.io "poolers.postgresql.cnpg.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes (retried 5 times).
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment] 2024-05-07 13:23
Hi @DevBey 

This was declared in the release notes some weeks ago here https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/release_notes/v1.22.md#changes meaning that 1.23.0 is also affected

Closing since it's not a bug

Regards,

**Closed by sxd** 2024-05-07 13:23 UTC
Labels: triage

**Comment by DevBey** [comment] 2024-05-07 15:32
apologies @sxd 
 for my ignorance, but i am still not able to understand/find if this has been fixed ?? or we can't use argocd with cloud native right ?? 

the charts work well directly using helm.

**Comment by danpe** [comment] 2024-08-07 11:11
@sxd Although it shows in the changelog, it still won't let me deploy cnpg using `kubectl apply -f cnpg-1.23.yaml` ?

**Comment by sxd** [comment] 2024-08-07 11:38
@danpe no

**Comment by danpe** [comment] 2024-08-07 12:33
OK I see `kubectl apply --server-side -f ...` is required, thank you 🙏

**Comment by AntoineMicheaOpencell** [comment] 2024-09-04 20:45
For argocd applications don't forget to use:
```
  syncPolicy:
    syncOptions: 
      - ServerSideApply=true
```
