### ISSUE TITLE
[Bug]: kubectl cnpg psql doesn't pass `--context` to kubectl

### ISSUE THREAD

**Issue by redbaron** [cloudnative-pg/cloudnative-pg#4332] opened 2024-04-18 08:32 UTC
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

Helm

### What happened?

`kubectl cnpg psql --context X`  doesn't pass `--context X` to underneath kubectl invocation , as a result psql doesn't work unless context X is selected as default in $KUBECONFIG

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment] 2024-04-18 08:38
Hi @redbaron 

The flag `--context` is a global flag, can you test passing this flag before the `psql` command ?

Regards,

**Comment by redbaron** [comment] 2024-04-18 08:41
> Hi @redbaron
> 
> The flag `--context` is a global flag, can you test passing this flag before the `psql` command ?
> 
> Regards,

Tried multiple variants, same result.

```
$ kubectl  cnpg --context "X" -n s-foobar psql s-foobar-3cbd
Error from server (NotFound): namespaces "s-foobar" not found
$ kubectl ctx X
Switched to context "X".
$ kubectl  cnpg --context "X" -n s-foobar psql s-foobar-3cbd
psql (15.6 (Debian 15.6-1.pgdg110+2))
Type "help" for help.

postgres=# 

```

**Comment by sxd** [comment] 2024-04-18 09:38
@redbaron 

Thanks for reporting this, I can confirm it's a bug! I'll add some more labels asking for help on a PR

Best Regards!

**Comment by armru** [comment] 2024-06-17 09:36
Unable to reproduce on the latest version

**Comment by redbaron** [comment] 2024-06-17 09:42
Still reproducible for me on 

```
$ kubectl cnpg version                                                           
Build: {Version:1.23.2 Commit:4bef8412 Date:2024-06-12}
```

**Comment by gbartolini** [comment] 2024-12-04 17:16
This is a duplicate of #6227 - closing it.

**Closed by gbartolini** 2024-12-04 17:16 UTC
Labels: bug :bug:, good first issue, help wanted :sos:
