### ISSUE TITLE
[Bug]: CNPG 1.23 - cannot create Cluster auxiliary objects: expected pointer, but got invalid

### ISSUE THREAD

**Issue by MichaluxPL** [cloudnative-pg/cloudnative-pg#4389] opened 2024-04-26 12:28 UTC
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

michaluxpl@gmail.com

### Version

1.23.0

### What version of Kubernetes are you using?

1.26

### What is your Kubernetes environment?

Self-managed: RKE

### How did you install the operator?

YAML manifest

### What happened?

During every cluster provisioning operator logs an error:
{"level":"error","ts":"2024-04-26T08:35:44Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"[postgresql.cnpg.io](http://postgresql.cnpg.io/)","controllerKind":"Cluster","Cluster":{"name":"testcluster","namespace":"test"},"namespace":"test","name":"testcluster,"reconcileID":"b380ddb3-45ae-40f6-bb4d-5ae8eaaa726e","error":"cannot create Cluster auxiliary objects: expected pointer, but got invalid kind","stacktrace":"[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler)\n\tpkg/mod/[sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:329\](http://sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:329%5C)[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem)\n\tpkg/mod/[sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266\](http://sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266%5C)[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2)\n\tpkg/mod/[sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go](http://sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go): 227"}
No init pod is created.
It appears that, without enablepodmonitor: true no such error occurs and new cluster can be created.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phisco** [comment] 2024-04-26 13:46
duplicate of https://github.com/cloudnative-pg/cloudnative-pg/issues/4286

**Comment by Ornias1993** [comment] 2024-04-26 15:56
> duplicate of #4286

Correct, can be closed.

**Closed** 2024-05-06 09:51 UTC
Labels: triage
