### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by edib** [cloudnative-pg/cloudnative-pg#3452] opened 2023-12-03 21:36 UTC
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

kokdemir@gmail.com

### Version

1.21.1

### What version of Kubernetes are you using?

other (unsupported)

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

I have created cluster without enableSuperuserAccess=false default values. Then I wanted to change the postgres password manually. I discovered that the password is periodically resetted to null. I have created superusersecret secret resource and define it in cluster definition. I discovered again that it did not work. Then I have set enableSuperuserAccess=true in cluster definition. It restarted all nodes. I wanted to check if it works. it seems it does not  work.  

### Cluster resource

```shell
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
type: kubernetes.io/basic-auth
stringData:
    username: "postgres"
    password: "password"

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres
spec:
  enableSuperuserAccess: true
  instances: 3
  superuserSecret:
    name: postgres-superuser
  imageName: pg-custom-pg:16.0
  bootstrap:
    initdb:
      dataChecksums: true
      encoding: 'UTF8'
      localeCollate: 'tr_TR.UTF-8'
      localeCType: 'tr_TR.UTF-8'
  storage:
    size: 10Gi
  postgresql:
    pg_hba:
      - host all all all md5
    parameters:
      password_encryption: "md5"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by litaocdl** [comment] 2023-12-11 06:02
@edib Can we close this ticket as you mentioned it works in slack chat ?

**Comment by litaocdl** [comment] 2023-12-18 03:20
@edib I close the ticket as it is not a bug, feel free to open new one if you have new findings.

**Closed by litaocdl** 2023-12-18 03:20 UTC
Labels: triage
