### ISSUE TITLE
[Bug]: Unable to change datestyle from custom paremeters as it conflicts

### ISSUE THREAD

**Issue by samip5** [cloudnative-pg/cloudnative-pg#4524] opened 2024-05-14 03:20 UTC
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.23.1

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

I tried to set the `datestyle: iso, dmy, mdy` in postgresql.parameters in my cluster definition, but ended with it erroring.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  creationTimestamp: "2024-05-08T02:09:38Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: cloudnative-pg-cluster
    app.kubernetes.io/name: cloudnative-pg-cluster
    app.kubernetes.io/part-of: cloudnative-pg
    kustomize.toolkit.fluxcd.io/name: cnpg-cluster
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: postgres16
  namespace: databases
  resourceVersion: "5111002"
  uid: 8bd09f00-2248-4c47-9673-b13b1f9c17b4
spec:
  affinity:
    enablePodAntiAffinity: true
    nodeSelector:
      kubernetes.io/arch: amd64
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  backup:
    barmanObjectStore:
      data:
        compression: bzip2
      destinationPath: s3://cnpg-main/
      endpointURL: https://s3.skym.fi
      s3Credentials:
        accessKeyId:
          key: aws-access-key-id
          name: cloudnative-pg-secret
        secretAccessKey:
          key: aws-secret-access-key
          name: cloudnative-pg-secret
      serverName: postgres16-v3
      wal:
        compression: bzip2
        maxParallel: 4
    retentionPolicy: 30d
    target: prefer-standby
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
  enablePDB: true
  enableSuperuserAccess: true
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-18
  instances: 2
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
    podMonitorMetricRelabelings:
    - action: replace
      sourceLabels:
      - cluster
      targetLabel: cnpg_cluster
    - action: labeldrop
      regex: cluster
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      datestyle: iso, dmy, mdy
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_connections: "600"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_buffers: 512MB
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 20Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-secret
  switchoverDelay: 3600
status:
  availableArchitectures:
  - goArch: amd64
    hash: 94527128605ac5100415106fe26c480531d094b3f36626e562a8135f342b89e4
  - goArch: arm64
    hash: 9b7b08592e917ed3b20bb3ae404ea4c0c958bdee73e5411c452d6c464d77f0b4
  certificates:
    clientCASecret: postgres16-ca
    expirations:
      postgres16-ca: 2024-08-06 02:04:38 +0000 UTC
      postgres16-replication: 2024-08-06 02:04:38 +0000 UTC
      postgres16-server: 2024-08-06 02:04:38 +0000 UTC
    replicationTLSSecret: postgres16-replication
    serverAltDNSNames:
    - postgres16-rw
    - postgres16-rw.databases
    - postgres16-rw.databases.svc
    - postgres16-r
    - postgres16-r.databases
    - postgres16-r.databases.svc
    - postgres16-ro
    - postgres16-ro.databases
    - postgres16-ro.databases.svc
    serverCASecret: postgres16-ca
    serverTLSSecret: postgres16-server
  cloudNativePGCommitHash: 336ddf53
  cloudNativePGOperatorHash: 94527128605ac5100415106fe26c480531d094b3f36626e562a8135f342b89e4
  conditions:
  - lastTransitionTime: "2024-05-14T02:56:15Z"
    message: Cluster Is Not Ready
    reason: ClusterIsNotReady
    status: "False"
    type: Ready
  - lastTransitionTime: "2024-05-08T02:18:51Z"
    message: Continuous archiving is working
    reason: ContinuousArchivingSuccess
    status: "True"
    type: ContinuousArchiving
  - lastTransitionTime: "2024-05-14T00:19:44Z"
    message: Backup was successful
    reason: LastBackupSucceeded
    status: "True"
    type: LastBackupSucceeded
  configMapResourceVersion:
    metrics:
      cnpg-default-monitoring: "46272"
  currentPrimary: postgres16-1
  currentPrimaryTimestamp: "2024-05-08T02:18:50.020151Z"
  firstRecoverabilityPoint: "2024-05-09T00:19:16Z"
  firstRecoverabilityPointByMethod:
    barmanObjectStore: "2024-05-09T00:19:16Z"
  healthyPVC:
  - postgres16-1
  - postgres16-2
  image: ghcr.io/cloudnative-pg/postgresql:16.1-18
  instanceNames:
  - postgres16-1
  - postgres16-2
  instances: 2
  instancesReportedState:
    postgres16-1:
      isPrimary: false
    postgres16-2:
      isPrimary: false
  instancesStatus:
    replicating:
    - postgres16-1
    - postgres16-2
  lastSuccessfulBackup: "2024-05-14T00:19:41Z"
  lastSuccessfulBackupByMethod:
    barmanObjectStore: "2024-05-14T00:19:41Z"
  latestGeneratedNode: 2
  managedRolesStatus: {}
  phase: Waiting for the instances to become active
  phaseReason: Some instances are not yet active. Please wait.
  poolerIntegrations:
    pgBouncerIntegration: {}
  pvcCount: 2
  readService: postgres16-r
  secretsResourceVersion:
    applicationSecretVersion: "100075"
    clientCaSecretVersion: "100067"
    replicationSecretVersion: "100072"
    serverCaSecretVersion: "100067"
    serverSecretVersion: "100069"
    superuserSecretVersion: "98879"
  switchReplicaClusterStatus: {}
  targetPrimary: postgres16-1
  targetPrimaryTimestamp: "2024-05-08T02:09:38.390668Z"
  timelineID: 9
  topology:
    instances:
      postgres16-1: {}
      postgres16-2: {}
    nodesUsed: 2
    successfullyExtracted: true
  writeService: postgres16-rw
```

### Relevant log output

```shell
{"level":"info","ts":"2024-05-14T03:16:59Z","logger":"postgres","msg":"2024-05-14 03:16:59.652 UTC [22] LOG:  invalid value for parameter \"DateStyle\": \"iso, dmy, mdy\"","pipe":"stderr","logging_pod":"postgres16-2"}
{"level":"info","ts":"2024-05-14T03:16:59Z","logger":"postgres","msg":"2024-05-14 03:16:59.652 UTC [22] DETAIL:  Conflicting \"datestyle\" specifications.","pipe":"stderr","logging_pod":"postgres16-2"}
{"level":"info","ts":"2024-05-14T03:16:59Z","logger":"postgres","msg":"2024-05-14 03:16:59.652 UTC [22] FATAL:  configuration file \"/var/lib/postgresql/data/pgdata/custom.conf\" contains errors","pipe":"stderr","logging_pod":"postgres16-2"}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment] 2024-05-14 06:48
Hi @samip5 

This is just a wrong setting of a postgresql parameter I suggest you to read this documentation https://www.postgresql.org/docs/16/datatype-datetime.html and this https://www.postgresql.org/docs/16/runtime-config-client.html#RUNTIME-CONFIG-CLIENT-FORMAT to understand which will be a proper value for your needs

Closing now since it's not a bug but a misconfiguration 

Regards!

**Closed by sxd** 2024-05-14 06:48 UTC
