### ISSUE TITLE
[Bug]: WATCH_NAMESPACE does not restrict the operator to specified namespaces

### ISSUE THREAD

**Issue by yuha0** [cloudnative-pg/cloudnative-pg#3649] opened 2023-12-29 07:31 UTC
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.22.0

### What version of Kubernetes are you using?

1.27

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

The configuration option `WATCH_NAMESPACE` could not restrict the controller to specified namespaces. I set `WATCH_NAMESPACE=cnpg-system` but the controller still tried to list namespaced resources in all namespaces.

Per documentation and helm chat, it is an option provided to the users, which seem to imply the operator can operate within certain namespaces.

### Relevant log output

```shell
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Starting CloudNativePG Operator","version":"1.22.0","build":{"Version":"1.22.0","Commit":"86b9dc80","Date":"2023-12-21"}}
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Listening for changes on all namespaces"}
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Loading configuration from ConfigMap","namespace":"cnpg-system","name":"cnpg-controller-manager-config"}
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Loading configuration from Secret","namespace":"cnpg-system","name":"cnpg-controller-manager-config"}
{"level":"info","ts":"2023-12-29T06:50:04Z","logger":"setup","msg":"Operator configuration loaded","configuration":{"webhookCertDir":"","watchNamespace":"cnpg-system","operatorNamespace":"cnpg-system","operatorPullSecretName":"cnpg-pull-secret","operatorImageName":"ghcr.io/cloudnative-pg/cloudnative-pg:1.22.0","postgresImageName":"ghcr.io/cloudnative-pg/postgresql:16.1","inheritedAnnotations":null,"inheritedLabels":null,"monitoringQueriesConfigmap":"cnpg-default-monitoring","monitoringQueriesSecret":"","enableInstanceManagerInplaceUpdates":false,"enableAzurePVCUpdates":false,"enablePodDebugging":false,"createAnyService":false}}
...
{"level":"info","ts":"2023-12-29T06:50:07Z","logger":"controller-runtime.metrics","msg":"Serving metrics server","bindAddress":":8080","secure":false}
{"level":"info","ts":"2023-12-29T06:50:07Z","msg":"pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User \"system:serviceaccount:cnpg-system:cnpg-manager\" cannot list resource \"persistentvolumeclaims\" in API group \"\" at the cluster scope"}
{"level":"error","ts":"2023-12-29T06:50:07Z","msg":"pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.PersistentVolumeClaim: failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User \"system:serviceaccount:cnpg-system:cnpg-manager\" cannot list resource \"persistentvolumeclaims\" in API group \"\" at the cluster scope","stacktrace":"k8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\tpkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:147\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\tpkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:292\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/backoff.go:227\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\tpkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:290\nk8s.io/client-go/tools/cache.(*controller).Run.(*Group).StartWithChannel.func2\n\tpkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/wait.go:55\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\tpkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/wait.go:72"}
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YanniHu1996** [comment] 2024-01-02 07:38
Hi @yuha0 , I am not able to reproduce this issue,  here is my  procedure

1. Deploy the operator with 1,22.0
```sh
kubectl apply -f \
  https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.22/releases/cnpg-1.22.0.yaml
```

2. edit deployment 

```sh
kubectl get deployments.apps cnpg-controller-manager -oyaml | yq .spec.template.spec.containers.0
```
```yaml
args:
  - controller
  - --leader-elect
  - --config-map-name=cnpg-controller-manager-config
  - --secret-name=cnpg-controller-manager-config
  - --webhook-port=9443
command:
  - /manager
env:
  - name: OPERATOR_IMAGE_NAME
    value: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.0
  - name: OPERATOR_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: MONITORING_QUERIES_CONFIGMAP
    value: cnpg-default-monitoring
  - name: WATCH_NAMESPACE
    value: cnpg-system
image: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.0
imagePullPolicy: IfNotPresent
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /readyz
    port: 9443
    scheme: HTTPS
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
name: manager
ports:
  - containerPort: 8080
    name: metrics
    protocol: TCP
  - containerPort: 9443
    name: webhook-server
    protocol: TCP
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /readyz
    port: 9443
    scheme: HTTPS
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 10001
  runAsUser: 10001
  seccompProfile:
    type: RuntimeDefault
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
volumeMounts:
  - mountPath: /controller
    name: scratch-data
  - mountPath: /run/secrets/cnpg.io/webhook
    name: webhook-certificates
```

3. check the log 

```json
{
  "level": "info",
  "ts": "2024-01-02T07:35:29Z",
  "logger": "setup",
  "msg": "Starting CloudNativePG Operator",
  "version": "1.22.0",
  "build": {
    "Version": "1.22.0",
    "Commit": "86b9dc80",
    "Date": "2023-12-21"
  }
}
{
  "level": "info",
  "ts": "2024-01-02T07:35:29Z",
  "logger": "setup",
  "msg": "Listening for changes",
  "watchNamespaces": [
    "cnpg-system"
  ]
}
```

Anything I miss?

**Comment by yuha0** [comment] 2024-01-02 07:55
Hi @YanniHu1996 , the manifest applied in your first step contains [a clusterrole that gives the operator permission to list namespaced resources](https://github.com/cloudnative-pg/cloudnative-pg/blob/v1.22.0/releases/cnpg-1.22.0.yaml#L13224-L13234) like configmaps, secrets, PVCs in all namespaces. I think that's why you won't see the same error. 

You can check your cluster's audit log and see if the operator made requests to list resources in other namespaces, or, the way I managed to produce the error:

1. Remove PVC `list` permission from the ClusterRole.
2. Create a Role with permission to `list` PVC in `cnpg-system` namespace and bind to the service account.
3. Configure the operator with `WATCH_NAMESPACE=cnpg-system` and deploy.
4. In theory, now it should just work happily without printing permission errors (It is configured to watch a single namespace, and has permission to list PVCs in that exact namespace). But it will actually produce the error logs shown in my initial report.

**Comment by YanniHu1996** [comment] 2024-01-03 10:19
Hi @yuha0  I am sorry for being unable to replicate the issue with the provided steps. Could you please clarify step 3, specifically on how to set `WATCH_NAMESPACE=cnpg-system`?

**Comment by nickvth** [comment] 2024-04-15 12:32
It's not working with the helm chart, please add ENV WATCH_NAMESPACE if set.

https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/templates/deployment.yaml

**Comment by Stevenpc3** [comment] 2024-05-28 17:54
I am also requiring this namespace control.  If we cannot restrict it then we cannot use the operator 😢 

@nickvth the helm chart supports this via --set config.data and passing a list.  You can use this as a file override.  See here that mentions it in the values.yaml https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml#L64 and here that passes in the ENV via a configmap https://github.com/cloudnative-pg/charts/blob/f7e6ddc2b3a1211588d07d723e9e3dfcb4f66485/charts/cloudnative-pg/templates/config.yaml#L29

I made an ```override.yaml``` to pass in with the contents

```
config:
  data:
    WATCH_NAMESPACE: namespace-a,namespace-b
```

then I made two namespaces to match:  namespace-a and namespace-b and one to ignore "ignoreme"

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/6076207/824b6561-386d-4609-947c-3b6e6ddb0a9c)

Then I deployed the operator using the helm chart https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg to the default namespace

```
helm repo add cnpg https://cloudnative-pg.github.io/charts
helm upgrade -i cnpg -n default cnpg/cloudnative-pg -f override.yaml
```

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/6076207/099402bc-937b-42b7-a79f-4c69fc2eb228)

You can see in the logs that it watches ALL namespaces but the configuration was passed in to the operator.

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/6076207/1f1fc017-700d-4a7e-b41f-d38dad171ace)

The configmap has the correct values 
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/6076207/f8502e0b-2e26-4605-914a-d16886c5ed0b)

I was unable to exec into the pod to verify the ENV values but you can at least see that the values listed in decribe pod do not include WATCH_NAMESPACE

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/6076207/17d5c67e-3cf9-4868-b3ee-777db98f4dd9)

If you check the logs above you can see that it prints "wathcing all namespaces" BEFORE it loads the configurations!!!  

It might (for the helm charts process describe) at least be an order of operations thing.  The operator should load configurations before deciding which namespace to watch.

**Comment by sxd** [comment] 2024-05-31 10:15
Hi 

This is working on the operator and I wasn't able to reproduce, if someone can reproduce in a vanilla deployment of the operator, please update this ticket, in the meantime I'll close it

Regards!

**Closed by sxd** 2024-05-31 10:15 UTC
Labels: triage
